version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.11"
  commands:
    - pip install uv
    - uv sync --extra docs
    - uv run sphinx-build -b html docs $READTHEDOCS_OUTPUT/html

sphinx:
  configuration: docs/conf.py
